version: '3'

services:
  webapi:
    restart: always
    image: coreservice:latest
    container_name: coreservice
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
       
